"""create user and blog table migrations

Revision ID: 615fe42ec9a1
Revises:
Create Date: 2023-10-27 17:38:35.314564

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "615fe42ec9a1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
